# Generated by Django 6.0.5 on 2026-05-27 18:00

import airport.models.reserva
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'db_table': 'aerolinea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=50)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'db_table': 'aeropuerto',
                'ordering': ['pais', 'ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('num_pasaporte', models.CharField(max_length=20, unique=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'db_table': 'pasajero',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'En mantenimiento'), ('retirada', 'Retirada')], default='activa', max_length=20)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeronaves', to='airport.aerolinea')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'db_table': 'aeronave',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('terminal', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertas', to='airport.aeropuerto')),
            ],
            options={
                'verbose_name': 'Puerta',
                'verbose_name_plural': 'Puertas',
                'db_table': 'puerta',
                'ordering': ['terminal', 'codigo'],
                'unique_together': {('aeropuerto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('auxiliar', 'Auxiliar de vuelo'), ('jefe_cabina', 'Jefe de cabina')], max_length=20)),
                ('num_licencia', models.CharField(max_length=30, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulantes', to='airport.aerolinea')),
            ],
            options={
                'verbose_name': 'Tripulante',
                'verbose_name_plural': 'Tripulantes',
                'db_table': 'tripulante',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('salida_programada', models.DateTimeField()),
                ('llegada_programada', models.DateTimeField()),
                ('salida_real', models.DateTimeField(blank=True, null=True)),
                ('llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('embarcando', 'Embarcando'), ('despegado', 'Despegado'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='programado', max_length=20)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='airport.aerolinea')),
                ('aeronave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos', to='airport.aeronave')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_llegada', to='airport.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_salida', to='airport.aeropuerto')),
                ('puerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos', to='airport.puerta')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'db_table': 'vuelo',
                'ordering': ['salida_programada'],
                'unique_together': {('aerolinea', 'numero_vuelo', 'salida_programada')},
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('tecnico', 'Técnico'), ('medico', 'Médico'), ('seguridad', 'Seguridad'), ('meteorologico', 'Meteorológico'), ('operacional', 'Operacional'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('reportado_en', models.DateTimeField(auto_now_add=True)),
                ('estado_resolucion', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='abierto', max_length=20)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incidente',
                'ordering': ['-reportado_en'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_asiento', models.CharField(max_length=5)),
                ('clase', models.CharField(choices=[('economica', 'Económica'), ('ejecutiva', 'Ejecutiva'), ('primera', 'Primera clase')], default='economica', max_length=20)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('abordada', 'Abordada')], default='pendiente', max_length=20)),
                ('codigo_reserva', models.CharField(default=airport.models.reserva.generar_codigo_reserva, max_length=6, unique=True)),
                ('reservado_en', models.DateTimeField(auto_now_add=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='airport.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-reservado_en'],
                'unique_together': {('vuelo', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTripulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol_asignado', models.CharField(max_length=50)),
                ('tripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='airport.tripulante')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tripulacion', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Asignación de tripulación',
                'verbose_name_plural': 'Asignaciones de tripulación',
                'db_table': 'asignacion_tripulacion',
                'unique_together': {('vuelo', 'tripulante')},
            },
        ),
    ]
