# Generated by Django 6.0.5 on 2026-06-26 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('capacidad_puertas', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En mantenimiento')], default='activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to='airport.aeropuerto')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'ordering': ['aeropuerto', 'codigo'],
            },
        ),
    ]
