# Generated by Django 6.0.5 on 2026-06-25 04:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('frequent_flyer', 'Viajero frecuente'), ('vip', 'VIP'), ('discapacidad', 'Pasajero con discapacidad'), ('menor_no_acompanado', 'Menor no acompañado'), ('asistencia_medica', 'Requiere asistencia médica'), ('embarazada', 'Embarazada'), ('deportista', 'Deportista / equipo'), ('diplomatico', 'Diplomático')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_asistencia', models.BooleanField(default=False)),
                ('beneficios', models.TextField(blank=True, help_text='Descripción de beneficios o servicios especiales asociados.')),
                ('activa', models.BooleanField(default=True)),
                ('pasajeros', models.ManyToManyField(blank=True, related_name='categorias', to='airport.pasajero')),
            ],
            options={
                'verbose_name': 'Categoría de Pasajero',
                'verbose_name_plural': 'Categorías de Pasajero',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mano', 'Equipaje de mano'), ('bodega', 'Equipaje de bodega'), ('especial', 'Equipaje especial (bicicleta, instrumento, etc.)')], default='bodega', max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('codigo_etiqueta', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_vuelo', 'En vuelo'), ('entregado', 'Entregado'), ('perdido', 'Perdido'), ('dañado', 'Dañado'), ('retenido', 'Retenido por aduana')], default='registrado', max_length=20)),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Cobro extra por sobrepeso o equipaje especial.', max_digits=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipajes', to='airport.reserva')),
            ],
            options={
                'verbose_name': 'Equipaje',
                'verbose_name_plural': 'Equipajes',
                'ordering': ['reserva', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso de vuelo'), ('cancelacion', 'Cancelación de vuelo'), ('cambio_puerta', 'Cambio de puerta'), ('embarque', 'Llamado a embarque'), ('confirmacion', 'Confirmación de reserva'), ('recordatorio', 'Recordatorio de vuelo'), ('equipaje', 'Estado de equipaje'), ('otro', 'Otro')], max_length=20)),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico'), ('sms', 'SMS'), ('push', 'Notificación push'), ('sistema', 'Sistema interno')], default='email', max_length=10)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('fallida', 'Fallo en el envío')], default='pendiente', max_length=15)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='airport.pasajero')),
                ('vuelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asiento', models.CharField(max_length=5)),
                ('puerta_embarque', models.CharField(max_length=10)),
                ('grupo_embarque', models.CharField(blank=True, max_length=5)),
                ('hora_limite_embarque', models.DateTimeField()),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('usada', 'Usada — pasajero abordó'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='generada', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('check_in_online', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_embarque', to='airport.reserva')),
            ],
            options={
                'verbose_name': 'Tarjeta de Embarque',
                'verbose_name_plural': 'Tarjetas de Embarque',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='TipoAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(blank=True, max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('narrow', 'Narrow-body (pasillo único)'), ('wide', 'Wide-body (doble pasillo)'), ('regional', 'Regional / turbohélice'), ('cargo', 'Carguero'), ('privado', 'Aviación privada')], max_length=20)),
                ('capacidad_pasajeros_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad_pasajeros_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('autonomia_km', models.PositiveIntegerField(help_text='Alcance máximo en kilómetros.')),
                ('velocidad_crucero_kmh', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('en_produccion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aeronave',
                'verbose_name_plural': 'Tipos de Aeronave',
                'ordering': ['fabricante', 'modelo'],
                'unique_together': {('fabricante', 'modelo')},
            },
        ),
    ]
