# Generated by Django 6.0.5 on 2026-06-26 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PistaAterrizaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=10)),
                ('longitud_metros', models.IntegerField()),
                ('superficie', models.CharField(choices=[('asfalto', 'Asfalto'), ('concreto', 'Concreto'), ('cesped', 'Césped'), ('grava', 'Grava')], default='asfalto', max_length=20)),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('cerrada', 'Cerrada'), ('mantenimiento', 'En mantenimiento')], default='operativa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='airport.aeropuerto')),
            ],
            options={
                'verbose_name': 'Pista de Aterrizaje',
                'verbose_name_plural': 'Pistas de Aterrizaje',
                'ordering': ['aeropuerto', 'identificador'],
            },
        ),
    ]
