# Generated by Django 6.0.5 on 2026-06-26 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_pistaaterrizaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('aterrizaje', 'Aterrizaje'), ('despegue', 'Despegue'), ('prueba', 'Prueba')], max_length=20)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='airport.pistaaterrizaje')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_pista', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Asignación de Pista',
                'verbose_name_plural': 'Asignaciones de Pista',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
