# Generated by Django 6.0.5 on 2026-06-26 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_asignacionpista'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioVuelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_vuelo_base', models.CharField(max_length=20)),
                ('hora_salida', models.TimeField()),
                ('dias_operacion', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='airport.aerolinea')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_destino', to='airport.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_origen', to='airport.aeropuerto')),
            ],
            options={
                'verbose_name': 'Horario de Vuelo',
                'verbose_name_plural': 'Horarios de Vuelo',
                'ordering': ['hora_salida'],
            },
        ),
    ]
