# Generated by Django 6.0.5 on 2026-06-26 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_horariovuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaVuelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_secuencia', models.IntegerField()),
                ('hora_llegada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aeropuerto_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='airport.aeropuerto')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='airport.vuelo')),
            ],
            options={
                'verbose_name': 'Escala de Vuelo',
                'verbose_name_plural': 'Escalas de Vuelo',
                'ordering': ['vuelo', 'numero_secuencia'],
                'unique_together': {('vuelo', 'numero_secuencia')},
            },
        ),
    ]
