# Generated by Django 6.0.5 on 2026-06-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_categoriapasajero_equipaje_notificacion_and_more'),
        ('airport', '0006_escalavuelo'),
    ]

    operations = [
    ]
