# Generated by Django 5.2.16 on 2026-07-11 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0007_merge_20260626_1540'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('login', 'Login'), ('logout', 'Logout'), ('cambio_estado', 'Cambio de estado'), ('exportar', 'Exportar')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'audit_log',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionTripulante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_aeronave_habilitado', models.CharField(blank=True, help_text='Modelo de aeronave habilitado. Ej: Boeing 737, Airbus A320.', max_length=100)),
                ('tipo', models.CharField(choices=[('licencia_piloto', 'Licencia de piloto'), ('habilitacion_tipo', 'Habilitación de tipo'), ('cert_medico', 'Certificado médico'), ('recurrente', 'Recurrente'), ('emergencias', 'Emergencias'), ('servicio_cabina', 'Servicio de cabina'), ('seguridad', 'Seguridad')], max_length=20)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencida', 'Vencida'), ('suspendida', 'Suspendida'), ('renovada', 'Renovada')], default='vigente', max_length=20)),
                ('numero_certificado', models.CharField(max_length=50, unique=True)),
                ('entidad_emisora', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='airport.tripulante')),
            ],
            options={
                'verbose_name': 'Certificación de tripulante',
                'verbose_name_plural': 'Certificaciones de tripulante',
                'db_table': 'certificacion_tripulante',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoAeronave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('revision_a', 'Revisión A'), ('revision_b', 'Revisión B'), ('revision_c', 'Revisión C'), ('emergencia', 'Emergencia')], max_length=20)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_progreso', 'En progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('postergado', 'Postergado')], default='programado', max_length=20)),
                ('descripcion', models.TextField()),
                ('tecnico_responsable', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin_estimada', models.DateTimeField()),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('horas_fuera_servicio', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='airport.aeronave')),
                ('aeropuerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_aeronave', to='airport.aeropuerto')),
            ],
            options={
                'verbose_name': 'Mantenimiento de aeronave',
                'verbose_name_plural': 'Mantenimientos de aeronave',
                'db_table': 'mantenimiento_aeronave',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC'), ('dni', 'DNI')], default='cedula', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], default='', max_length=25)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('operador', 'Operador'), ('supervisor', 'Supervisor'), ('analista', 'Analista'), ('tecnico', 'Técnico'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('foto_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aeropuerto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuario', to='airport.aeropuerto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'perfil_usuario',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('expirado', 'Expirado'), ('cerrado', 'Cerrado')], max_length=20)),
                ('token_jti', models.CharField(blank=True, db_index=True, max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de usuario',
                'verbose_name_plural': 'Sesiones de usuario',
                'db_table': 'sesion_usuario',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
