# Generated by hand to add the profile photo field (Pillow required).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0008_auditlog_certificaciontripulante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
