# Generated by hand to add la foto (URL) del aeropuerto.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0009_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='foto_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
