# Generated by hand para la nueva tabla de banners promocionales.

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0010_aeropuerto_foto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner promocional',
                'verbose_name_plural': 'Banners promocionales',
                'db_table': 'banner_promocional',
                'ordering': ['clave'],
            },
        ),
    ]
