# Generated by hand: agrega titulo/texto a BannerPromocional para poder
# editar también el texto de las tarjetas del carrusel público y del
# encabezado del login (no solo la imagen).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0011_bannerpromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpromocional',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerpromocional',
            name='texto',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
