# Generated by hand: agrega precio_base + configuración de clases de
# cabina (filas_primera/filas_ejecutiva) a Vuelo, y el precio "congelado"
# en el momento de la reserva a Reserva.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0012_bannerpromocional_titulo_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='filas_primera',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='filas_ejecutiva',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
