# Generated by hand: reemplaza filas_primera/filas_ejecutiva (rango de
# filas) por asientos_primera/asientos_ejecutiva (lista exacta de códigos
# de asiento), para permitir que el admin elija asientos puntuales en el
# mapa en vez de solo un número de filas desde el frente del avión.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0013_vuelo_precio_reserva_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='filas_primera',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='filas_ejecutiva',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='asientos_primera',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='asientos_ejecutiva',
            field=models.TextField(blank=True, default=''),
        ),
    ]
