# Generated by hand: permite que una Reserva cubra varios pasajeros y
# varios asientos a la vez (grupo de viaje), en vez de un solo pasajero
# con un solo asiento por registro.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0014_vuelo_asientos_por_clase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_asiento',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pasajeros_adultos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pasajeros_ninos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pasajeros_bebes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
