# Generated by hand to add banner image file upload (Pillow required, ya
# usado por 0009_perfilusuario_foto.py).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0015_reserva_multi_pasajeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpromocional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
