# Generated by hand to add aeropuerto image file upload (Pillow required,
# ya usado por 0009_perfilusuario_foto.py y 0016_bannerpromocional_imagen.py).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0016_bannerpromocional_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aeropuertos/'),
        ),
    ]
