# Generated by hand to add el logo (archivo + URL) de la aerolínea, mismo
# patrón que 0010_aeropuerto_foto_url.py / 0017_aeropuerto_foto.py.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0017_aeropuerto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='aerolineas/'),
        ),
    ]
