# Generated by hand to add la foto (archivo + URL) de la aeronave, mismo
# patrón que 0017_aeropuerto_foto.py / 0018_aerolinea_logo.py.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0018_aerolinea_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='foto_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aeronave',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aeronaves/'),
        ),
    ]
