# Generated by hand: convierte Puerta.terminal de texto libre a una FK real
# a Terminal (antes eran dos tablas sin ninguna conexión — se podía escribir
# cualquier texto en Puerta.terminal sin que existiera de verdad en
# Terminal). El texto viejo se pierde (las puertas ya creadas quedan con
# terminal=None hasta reasignarlas a una Terminal real desde el panel
# admin); el nuevo campo es nullable a nivel de base de datos solo para no
# romper esas filas existentes al migrar.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0019_aeronave_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puerta',
            name='terminal',
        ),
        migrations.AddField(
            model_name='puerta',
            name='terminal',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='puertas',
                to='airport.terminal',
            ),
        ),
    ]
