# Generated by hand para la nueva tabla de contenido institucional editable
# (mismo patrón que 0011_bannerpromocional.py).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0020_puerta_terminal_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInstitucional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=60, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido institucional',
                'verbose_name_plural': 'Contenidos institucionales',
                'db_table': 'contenido_institucional',
                'ordering': ['clave'],
            },
        ),
    ]
