# Generated by hand para agregar imagen/imagen_url a contenido institucional
# (mismo patrón que 0016_bannerpromocional_imagen.py).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0021_contenidoinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoinstitucional',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinstitucional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contenido_institucional/'),
        ),
    ]
